### PR TITLE
Add iOS targets

### PR DESCRIPTION
**Pull request by lhoracek**
I want to add iOS support to this project so we can leverage the DSL in our KMP project, but struggling with way to test it at the moment. 

Feature request: #145

### CODE REVIEW

**Comment by jillesvangurp** [comment]
Thanks for this. Let me know how this stuff works on IOS; you're technically the first to try this on IOS probably.

**Comment by jillesvangurp** [comment]
It's not currently building. I don't have the IOS sdks installed on my laptop so I can't really test this.

**Comment by lhoracek** [comment]
This should fix it. I unintentionally broke Ktor dependencies for native target by adding this. I needed to split each native target and add dependencies explicitly. Changed dependency for macos to Darwin as well as it should be better fit.
There might be better solution but this builds ok now.
Will post some example outputs from iOS later today.

**Comment by lhoracek** [comment]
I saw json-dsls PR for simulator was merge, once kotlinx-serialization-extensions is updated as well and release, we can enable the ios simulators target here as well.

**Comment by lhoracek** [comment]
So I tested today, using only the search-dsls library to compose the query. Same output on iOS and Android.

**Pull request merged**
