### PR TITLE
Add support for Linux platform

### PR DESCRIPTION
**Pull request by szaffarano**
Fixes https://github.com/jillesvangurp/kt-search/issues/151

What I did was:
- Uncommented the gradle config code
- Include a small logic to add linker options (only for Linux source sets) relying on the `LDFLAG` environment variable.
- Add an actual class, `KtorRestClient.linux.kt` that uses `Curl`
- A few small changes to the build.gradle file removing warnings.
- I'm not sure whether it should be included in this PR (or should be included at all), but I also added a small [Nix](https://nixos.org/) flake to facilitate having a dev environment.

I only tested it (and it works pretty well, with no issues so far) on LinuxX64, both locally (my dev environment uses NixOS) and on docker images.

### CODE REVIEW

**Comment by jillesvangurp** [comment]
Still not passing in CI unfortunately, any ideas on how to fix this?

```
Run sudo apt-get install libcurl4-openssl-dev
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  libcurl4-doc libidn11-dev libkrb5-dev libldap2-dev librtmp-dev libssh2-1-dev
The following NEW packages will be installed:
  libcurl4-openssl-dev
0 upgraded, 1 newly installed, 0 to remove and 33 not upgraded.
Need to get 386 kB of archives.
After this operation, 1698 kB of additional disk space will be used.
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Ign:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcurl4-openssl-dev amd64 7.81.0-1ubuntu1.18
Ign:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcurl4-openssl-dev amd64 7.81.0-1ubuntu1.18
Ign:2 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libcurl4-openssl-dev amd64 7.81.0-1ubuntu1.18
Err:2 mirror+file:/etc/apt/apt-mirrors.txt jammy-updates/main amd64 libcurl4-openssl-dev amd64 7.81.0-1ubuntu1.18
  404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch mirror+file:/etc/apt/apt-mirrors.txt/pool/main/c/curl/libcurl4-openssl-dev_7.81.0-1ubuntu1.18_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

**Comment by jillesvangurp** [comment]
Also not really liking the nix/flake dependency. Can you get rid of that?

**Comment by jillesvangurp** [comment]
can you merge master? I removed the bit that attempts to install libcurl headers. Not sure if that is still needed for Linux support but wasn't working in any case.

**Comment by szaffarano** [comment]
> can you merge master? I removed the bit that attempts to install libcurl headers. Not sure if that is still needed for Linux support but wasn't working in any case.

oh, I've just pushed another change installing libcurl, because indeed it's needed

**Pull request merged**
