### PR TITLE
adds query rescoring

### PR DESCRIPTION
**Pull request by AnyRoad**
https://www.elastic.co/guide/en/elasticsearch/reference/8.13/filter-search-results.html#query-rescorer

### CODE REVIEW

**Comment by AnyRoad** [comment]
https://github.com/jillesvangurp/kt-search/pull/134/files#diff-a4db7e6283ba73279198bd117cb095caed7d9d83aedd3935fe7046cc88801d30 has to be applied first to succeed the tests

**Comment by jillesvangurp** [comment]
Hey, thanks for your pullrequests, I merged your other changes. So, you should be able to update this branch and get this one fixed.

**Comment by AnyRoad** [comment]
Hey, just updated from the master branch and all tests work fine.
Thank you!

**Comment by jillesvangurp** [comment]
Great, thanks for all the work you are putting in. I'll cut a release soon.

**Pull request merged**
